import img1 from '../img/Legend_of_zelda_cover_(with_cartridge)_gold.png'
import img2 from '../img/The_Legend_of_Zelda_A_Link_to_the_Past_SNES_Game_Cover.jpg'
import img3 from '../img/The_Legend_of_Zelda_Ocarina_of_Time.jpg'
import img4 from '../img/735d1bf0-a553-46e9-9827-7bda86467eca.jpg'
import img5 from '../img/Links_Awakening.png'
import img6 from '../img/The_Legend_of_Zelda_-_Majoras_Mask_Box_Art.jpg'
import img7 from '../img/Zelda_II_The_Adventure_of_Link_box.jpg'
import img8 from '../img/The_Legend_of_Zelda_The_Wind_Waker.jpg'
import img9 from '../img/The_Legend_of_Zelda_Twilight_Princess_Game_Cover.jpg'
import img10 from '../img/The_Legend_of_Zelda_Oracle_of_Seasons_and_Oracle_of_Ages_Game_Cover.jpg'
import img11 from '../img/The_Legend_of_Zelda_Spirit_Tracks_box_art.jpg'
import img12 from '../img/fc12439d-c475-4668-a5a3-3d270472c385.png'
import img13 from '../img/6056f1c9482d6bb243127b1b8f7b71d4.jpg'
import img14 from '../img/The_Legend_of_Zelda_Four_Swords_Adventures_Game_Cover.jpg'
import img15 from '../img/The_Legend_of_Zelda_Tri_Force_Heroes_Boxart.jpg'
import img16 from '../img/The_Legend_of_Zelda_Breath_of_the_Wild.jpg'
import img17 from '../img/The_Legend_of_Zelda_A_Link_Between_Worlds_NA_cover.jpg'
import img18 from '../img/cd-i-zelda-the-wand-of-gamelon.jpg'
import img19 from '../img/The_Legend_of_Zelda_A_Link_to_the_Past_&_Four_Swords_Game_Cover.jpg'
import img20 from '../img/The_Legend_of_Zelda_The_Minish_Cap_Game_Cover.jpeg'

export const gameCovers = [img1, img2, img3, img4, img5, img6, img7, img8, img9, img10, img11, img12, img13, img14, img15, img16, img17, img18, img19, img20]
